# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'YJShufflingScrollView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YJShufflingScrollView

  pod 'Masonry'
  pod 'SDWebImage'

  target 'YJShufflingScrollViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YJShufflingScrollViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
